name: Terraform CI for Dev Environment

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-dev:
    name: Terraform Plan + tfsec (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Format Check
      run: terraform fmt #-check

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Install tfsec
      run: |
          curl -sSL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

    - name: Run tfsec with SARIF output
      run: tfsec --format sarif --out tfsec-results.sarif

    - name: Upload tfsec SARIF to GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: tfsec-results.sarif

