name: Terraform CI for Dev Environment

on:
  push:
    branches: [main]
    paths:
      - 'environments/dev/**'
      - '.github/workflows/main.yml'
      
  pull_request:
    branches: [main]
    paths:
      - 'environments/dev/**'
      - '.github/workflows/main.yml'

jobs:
  terraform-dev:
    name: Terraform Plan + tfsec (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Format Check
      run: terraform fmt #-check

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Install tfsec
      run: |
        curl -sSL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
        chmod +x tfsec
        sudo mv tfsec /usr/local/bin/
        
    - name: Run tfsec and generate report
      id: tfsec
      run: |
        tfsec --format json --out tfsec-results.json

    - name: Upload tfsec report as artifact
      if: always()  # ensures this runs even if tfsec fails
      uses: actions/upload-artifact@v4
      with:
        name: tfsec-results
        path: environments/dev/tfsec-results.json

    - name: Upload tfsec report to S3
      if: always()
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        aws s3 cp tfsec-results.json s3://tfsec-logs-bucket/tfsec-results-$TIMESTAMP.json





