name: Terraform CI for Dev Environment

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-dev:
    name: Terraform Plan + tfsec (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Run tfsec Security Scan
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        additional_args: "--minimum-severity HIGH"
        working_directory: environments/dev
