name: Terraform Apply (Prod - Manual Confirmation)

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: "Type 'yes' to confirm you want to apply to production"
        required: true

jobs:
  terraform-apply-prod:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/prod

    steps:
    - name: Check confirmation input
      run: |
        if [ "${{ github.event.inputs.confirm_apply }}" != "yes" ]; then
          echo "You must confirm with 'yes' to apply to prod."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
